### ISSUE TITLE
Heading color does not match Google Material Design color pallete

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#117]
https://www.google.com/design/spec/style/color.html#color-color-palette

How about the one ETL has #3f51b5? 

We should unify at least this in viz, etl and web pages.

**Comment by jirihelmich** [comment]
Well, then I have to change it throughout the template I purchased, it can be done, but does it need to be so ugly? :)

**Comment by jakubklimek** [comment]
You can discuss the color with @skodape and @martinnec tomorrow ;) It can be any one of those :)

**Comment by jirihelmich** [comment]
The one I use is almost the Material Blue (Blue 500 #2196F3).

**Comment by jirihelmich** [comment]
Btw. Google Inbox uses the one I do, which is also not from the palette.

**Comment by jakubklimek** [comment]
OK, changed the web to Blue 500

**Comment by jirihelmich** [comment]
OK, will change as well. @skodape are you aware?

**Comment by skodape** [comment]
Yes, I am.

**Comment by jirihelmich** [comment]
:+1:
