### ISSUE TITLE
Support all RDF serializations

### ISSUE THREAD

**Issue by jirihelmich** [ldvm/LDVMi#122]

**Comment by jakubklimek** [comment]
Turtle and RDF/XML tested OK.

Trig (http://linked.opendata.cz/dump/CUZK_55-pravni-vztahy-listiny.trig) still not working.

**Comment by jirihelmich** [comment]
This was not implemented at all, I'm pretty surprised that RDF/XML went through... was it via upload or via URL?

**Comment by jakubklimek** [comment]
Via URL... I will check if this was due to content negotiation... http://publications.europa.eu/mdr/resource/authority/eu-programme/skos/eu-programme-skos.rdf

**Comment by jirihelmich** [comment]
Yes, that's what I thought...

**Comment by jakubklimek** [comment]
No, it is RDF/XML.

**Comment by jakubklimek** [comment]
And it works... strange :)

**Comment by jirihelmich** [comment]
Actually, that's a dependency on Virtuoso. I just forward the file there. Does it support TriG?

**Comment by jakubklimek** [comment]
It does through its internal <a href="http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtBulkRDFLoader">bulk load functions</a>. 
Quads are not supported through SPARQL Graph Store HTTP Protocol if that is what you are using.

**Comment by jirihelmich** [comment]
Currently yes. I did not want to change this before trying BlazeGraph.

**Comment by jirihelmich** [comment]
Moved to linkedpipes/visualizations#21
