### ISSUE TITLE
Improvements to Hierarchy visualizer

### ISSUE THREAD

**Issue by jirihelmich** [ldvm/LDVMi#61]
- [x] add a way to obtain embed link
- [x] ensure that URL changes when a user switches the visualization type
- [x] drop the requirement to use `a skos:conceptScheme` -> ` skos:inScheme []`
- [x] compute right menu based on `[] skos:inScheme ?x`

**Comment by jakubklimek** [comment]
Also, when I select a ConceptScheme, I can no longer select another one:
![image](https://cloud.githubusercontent.com/assets/718827/10508685/e2ea37c8-7328-11e5-8541-eda988580e04.png)

**Comment by jakubklimek** [comment]
Hmm... when I waited long enough (long enough to write an issue ;)) the list appeared:
![image](https://cloud.githubusercontent.com/assets/718827/10508718/16c04614-7329-11e5-9711-ea144c023864.png)
So... a missing "waiting" indication?

**Comment by jirihelmich** [comment]
Please, check https://github.com/ldvm/vocabulary/commit/00735e7b9354a11aa309d0c6fa5c40fe792ffe35
