### ISSUE TITLE
Some slices through a datacube yield empty result

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#70]
E.g. http://live.payola.cz:29080/visualize/datacube#/id/245?view=chart&chartType=line&isPolar=false&p=a21fad3d352c66998620dfcf8776744e

**Comment by jirihelmich** [comment]
Could you point me to the source data? As I have troubles to find a configuration, that would display some data.

**Comment by jakubklimek** [comment]
I think the problem could be that I have more than 1 value on 3 dimensions, which I think is not supported? However the configuration help message is not shown.
