### ISSUE TITLE
Discovery broken

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#75]
When I now run discovery on http://linked.opendata.cz and graphs:
```
http://data.czso.cz/resource/dataset/demography-in-regions-czech-republic-age-categories
http://data.czso.cz/resource/dataset/demography-in-regions-czech-republic-age-categories/vocabulary
http://linked.opendata.cz/resource/dataset/gregorian-year-labels
http://linked.opendata.cz/resource/dataset/ruian-labels
http://linked.opendata.cz/generated/dataset/codelist-age
http://linked.opendata.cz/resource/dataset/gregorian-day-labels
http://linked.opendata.cz/resource/dataset/sdmx-codelists
http://linked.opendata.cz/generated/dataset/codelist-age
```
It runs long and discoveres many pipelines. Maybe the "combine" switch is broken?

**Comment by jirihelmich** [comment]
In fact, it completely ignored the parameters, so it made a complete discovery.

**Comment by jakubklimek** [comment]
It seems that discovery now does not work at all :)

**Comment by jirihelmich** [comment]
So much for commits from public transport.
Thu, 22 Oct 2015 v 09:33 odesílatel Jakub Klímek <notifications@github.com>
napsal:

**Comment by jirihelmich** [comment]
It was working for multiple endpoints, not for a single one, sorry.
