### ISSUE TITLE
DataCube visualizer does not store dimension order properly

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#77]
<a href="http://live.payola.cz:29080/visualize/datacube#/id/246?view=chart&chartType=line&isPolar=false&p=e826bd9d9b0ac4b92347a74c7b792cbf">This viz</a> had an altered dimension ordering. No won the X axis there is sex. Before, there was the time dimension.

**Comment by jakubklimek** [comment]
However, it does not happen always... e.g. <a href="http://live.payola.cz:29080/visualize/datacube#/id/244?view=chart&chartType=line&isPolar=false&p=119c4b014f9f469a4cfb08e60224700d&language=en">this viz</a> seems to have the ordering preserved.

**Comment by jakubklimek** [comment]
Today, it happen to me again, the dimensions got reordered... seems random

**Comment by jirihelmich** [comment]
Btw.: this is expected behaviour for partially ordered cubes. If you have e.g. 4D cube with 2 ordered and 2 unordered dimensions, let's say:

D1: 1
D2: -
D3: -
D4: 4

it will be ordered as follows:

D1 : 1
D4 : 4
D2: 100
D3: 101
