### ISSUE TITLE
Allow combining arbitrary datasources

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#79]
1 dataset can be either
  * SPARQL endpoint (with graphs)
  * Remote RDF (Turtle so far)
  * Upload RDF (Trutle so far)

I can have multiple datasets

This is related to https://github.com/ldvm/LDVMi/issues/68 as that could be partially resolved by this

**Comment by jirihelmich** [comment]
In progress in order to be able to close #68.

![image](https://cloud.githubusercontent.com/assets/174768/10680563/26ecf214-7921-11e5-9738-e937d00704e4.png)

**Comment by jirihelmich** [comment]
It compiles now, needs testing. I will do at least basic and then deploy it.
