### ISSUE TITLE
Sample OVM pipeline does not work

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#83]
1) Remote TTLs:
http://opendata.cz/ldvm/ovm-vocab.ttl
https://raw.githubusercontent.com/payola/ldvm/master/rdf/examples/ovm-obce-links.ttl
http://opendata.cz/ldvm/ovm.ttl
2) SPARQL: http://ruian.linked.opendata.cz/sparql

I click on discover and I wait and wait and wait

**Comment by jirihelmich** [comment]
The pipeline discovery works, Virtuoso Graph store is broken.
