### ISSUE TITLE
SPARQL Endpoint on HTTPS returns SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#90]
It seems that https://data.cssz.cz/fuseki/OD/query has a valid certificate...

```
ERROR: HttpException: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated: Unexpected error making the query: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
ERROR: Unexpected error making the query: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
```

**Comment by jirihelmich** [comment]
According to https://www.ssllabs.com/ssltest/analyze.html?d=data.cssz.cz, it should be fine. Looking into that later.

**Comment by jirihelmich** [comment]
List of their graphs: https://data.cssz.cz/fuseki/OD/query?default-graph-uri=&query=select+%3Fg+count+%28%3Fs%29+where+%7Bgraph+%3Fg+%7B%3Fs+%3Fp+%3Fo%7D%7D+group+by+%3Fg&format=text%2Fttl&timeout=0&debug=on

**Comment by jirihelmich** [comment]
Fixed.
