### ISSUE TITLE
Hierarchy visualizer - language support

### ISSUE THREAD

**Issue by jirihelmich** [ldvm/LDVMi#92]
- [ ] ability to change language via UI
- [ ] ability to change language via URL

**Comment by jakubklimek** [comment]
When visualizing https://raw.githubusercontent.com/openbudgets/datasets/master/greek-municipalities/codelist/athens-administrations.ttl, I see no label. (the language tags are *el*)

**Comment by jakubklimek** [comment]
Moved to https://github.com/linkedpipes/visualizations/issues/25
